zooniverse/scribes-of-the-cairo-geniza

src/components/App.jsx
src/components/ControlPanel.jsx
src/components/Dialog.jsx
src/ducks/field-guide.js
src/ducks/initialize.js
src/ducks/login.js
src/ducks/project.js
src/ducks/reducer.js
src/ducks/workflow.js

COOL! I think I did this right, and I'm pretty happy with how it has cleaned everything up. This PR abstracts all the core resources out to an initializer duck before rendering anything.
Let me know if something looks out of place here. It might be redundant to have an `initializerReady` prop as well as `INITIALIZER_STATUS` and also `login.initialized` (sp?) in another part of the code? Also, British "initialised" vs. American "initialized."
Also, some of these lines are general clean up with some of the ducks and removal of the unnecessary `popupbody` ref.

Fetch Core Resources Before Rendering

---

package.json
src/components/AnnotationsPane.jsx
src/components/SelectedAnnotation.jsx
src/components/Toolbar.jsx
src/containers/SubjectViewer.jsx
src/ducks/annotations.js
src/ducks/classification.js
src/ducks/reducer.js
src/ducks/subject-viewer.js
src/ducks/subject.js
src/styles/components/dialog.styl
src/styles/components/subject-viewer.styl
src/styles/components/toolbar.styl
src/styles/global/app-theme.styl

This PR could do a million more lines, but I've stopped it at this point to keep it from getting too large. Currently, this branch will create and store annotations, place those annotations in the Redux store, and open an annotation window. 
This branch does not save text or delete annotations. That functionality is best saved for a future PR to break things up. I would also like to combine a lot of the functionality between classifications and annotations (mainly updating the classification as annotations are stored and deleted), but I am going to wait on that work until after this is merged. 
There is also some information here such as storing some workflow info in a classification that returns `undefined` now but should be more functional once another current PR is merged.

Create Annotation Tool

---

src/components/AnnotationsPane.jsx
src/containers/SubjectViewer.jsx
src/lib/Utility.js
src/styles/components/subject-viewer.styl

This PR attempts to add touch events to the Subject Viewer, allowing a user with an iPad (for example) to perform the same actions as a user wielding a computer with a mouse.
Hey! I turns out I actually added touch sensing in `getPointerXY` in ASM, I just never hooked up the event listeners - so that's one major part of calculations already done. 👍 
```
SubjectViewer.getPointerXY(e) {
const boundingBox = this.getBoundingBox();
let clientX = 0;
let clientY = 0;
if (e.clientX && e.clientY) {
clientX = e.clientX;
clientY = e.clientY;
} else if (e.touches && e.touches.length > 0 && e.touches[0].clientX &&  //Hahaha noice
e.touches[0].clientY) {
clientX = e.touches[0].clientX;
clientY = e.touches[0].clientY;
}
...
}
```
Adding `<svg onTouchStart={this.onMouseDown} etc etc >` seems to do most …

Add Touch events to Subject Viewer

---

package.json

This PR adds the ability for Zooniverse devs to deploy to https://www.scribesofthecairogeniza.org/ by running `npm run deploy-production`
Self-merging.

Add Deploy-Production script

---

src/index.tpl.html
webpack.config.js

Oh IE11, how could we have forgotten about you? (Oh, right: we _tried really hard.)_ This PR adds some quick fixes that allows IE11 users to access Scribes, and, just as importantly, allows local devs to test the website on their VMs because nobody actually installs IE11 on their machines if not held at gunpoint.
- Added polyfill service. Same as ASM, FYI. Added at the end <body> for performance reasons.
- Added a config option in webpack that disables the host-checking security mechanism; without this `disableHostCheck` option, accessing the localhost from a VM would lead to a fatal `Invalid Host header` error when accessing the webpage.
Simple fix, ready for review.

IE11 Compatibility

---

src/components/SelectedAnnotation.jsx
src/containers/SubjectViewer.jsx
src/ducks/keyboard.js

This PR addressed comments made in #35. We had originally discussed disabling the script change buttons if the modern characters were shown, but this was adjusted to automatically hide modern characters if the script was changed (which seemed more intuitive).

Tweak Keyboard in the Annotation Box

---

package-lock.json
package.json
src/components/ActiveCard.jsx
src/components/CollectionsManager.jsx
src/components/ControlPanel.jsx
src/components/CribSheet.jsx
src/components/FavoritesButton.jsx
src/components/ProjectHeader.jsx
src/components/ScriptReferences.jsx
src/components/SelectedAnnotation.jsx
src/components/Toolbar.jsx
src/ducks/initialize.js
src/ducks/languages.js
src/ducks/reducer.js
src/locales/ar.js
src/locales/en.js
src/locales/he.js
src/styles/components/collections-manager.styl
src/styles/components/dialog.styl
src/styles/components/project-header.styl
src/styles/components/script-references.styl
src/styles/components/selected-annotation.styl

This PR sets up translations for the app and adds translations for the subject viewer. More translations will need to be added eventually for other content on the page. I decided to use `react-localize-redux` rather than `counterpart` because the former worked better with changing the language state and translations through Redux.
There are a few translations missing for the subject viewer which will need to be added eventually.

Implement SubjectViewer Translations

---

src/components/App.jsx
src/components/ControlPanel.jsx
src/components/FinishedPrompt.jsx
src/config.js
src/containers/ClassifierContainer.jsx
src/ducks/annotations.js
src/ducks/classification.js
src/ducks/subject.js
src/lib/get-session-id.js
src/styles/components/finished-prompt.styl
src/styles/global/round-toggle.styl

This should contain all of the functionality needed to confirm a classification can be submitted. 
The modal is similar to the component on ASM, with a couple exceptions.
1) Functionality does not yet exist to save a classification. Instead, this branch contains a bare bones version of classification submission. I'd like to revisit saved classifications anew in a future PR.
2) You may note some hard-coded text in the `FinishedPrompt` where the question is typed. In ASM, this text is retrieved directly from the workflow resource. In this PR, the text is hardcoded for styling reasons (paragraph break).

SubmitClassification Modal

---

src/components/ControlPanel.jsx
src/components/WorkInProgressPopup.jsx
src/containers/ClassifierContainer.jsx
src/containers/SubjectViewer.jsx
src/ducks/annotations.js
src/ducks/classification.js
src/ducks/initialize.js
src/ducks/reducer.js
src/ducks/subject.js
src/ducks/work-in-progress.js
src/ducks/workflow.js
src/locales/ar.js
src/locales/en.js
src/locales/he.js
src/styles/components/control-panel.styl
src/styles/components/work-in-progress-popup.styl

This PR adds the ability for users to save/resume their work in progress, by using the Save Progress button on the Classifier page.
- A `WorkInProgress` duck/function library has been added.
- For future-proofing I'm reorganising how we code our ducks, starting with WorkInProgress.
- Prerequisite (in this PR): the Workflow and/or Subject duck will need to be updated to better follow a lifecycle Project-Workflow-Subject-Classification dependency lifecycle.
- This is because when a save project is loaded, it needs to pick a specific workflow, then pick a specific subject, in that order - this may short-circuit the way we currently baked workflow-subject fetch assumptions, if we're not careful.
- When a user visits the Classifier, check if the user has a saved work in progress.
- If nothing, …

"Save Progress" feature

---

package-lock.json
webpack.config.js

This PR fixes a mistake I added in PR #58 , which prevent `npm start` from compiling the website for localhost.
In PR #58, I introduced the `import { favicon } from './images/favicon.ico'` and `import { robots } from './robots.txt'` to `/src/index.js` so Webpack could bundle the the files.
This worked fine for `npm run build` because I remembered to add file-loaders for `ico` and `txt` files in `webpack.production.config.js`
Unfortunately, I forgot to add the file-loaders in `webpack.config.js`, so when trying to start our website on localhost, Webpack had no idea what to do with `favicon.ico` and `robots.txt`
Fix, obviously, was to update webpack.config.js.
Merging!

Fix Webpack for localhost

---

src/ducks/subject.js

This PR fixes an issue I accidentally introduced in commit https://github.com/zooniverse/scribes-of-the-cairo-geniza/commit/f1308d327cffa7663ceb3e492334e22068e68152 . Without this PR, once we cannot _progress past the second item_ in a Subject queue.
This was due to a branch of `fetchSubject()` where an updated copy of the queue is created via `const updatedQueue = getState().subject.queue.slice()`, but instead of updating the store with the _updated, shorter_ queue, I updated it with the _original_ queue instead. Whoops!
Merging this fix ASAP.

Fix Subject Queue

---

src/components/ControlPanel.jsx
src/ducks/subject-viewer.js
src/ducks/subject.js

This PR adds functionality to the "Transcribe Page Reverse" button on the Classifier Page's toolbar. As it says on the tin, it flips the page shows the other side, allowing the users a whole new image to annotate. 
- This assumes that Subject in Scribes of the Cairo Geniza has EXACTLY two images, corresponding to the front page and the back page. (Each image = a "frame", in code terms)
- As a result, each annotation/transcription submitted in the Classification will have a `frame` value, which indicates which page the annotation/transcription was made on.
- We're using a 0-index, so frame 0 is for first front page, and frame 1 is for the reverse page.
Surprisingly, the groundwork for frame switching is already well baked into the project code, and not much else is needed. Classifications …

Frame Switching - Allow Switching Between Front Page and Reverse Page

---

src/config.js

This PR prepares Scribes of the Cairo Geniza for deployment to production at https://www.scribesofthecairogeniza.org.
- In particular, this PR adds a Zooniverse App ID so **users can sign in to the website**
- External dependency: the website needs to be added to the Zooniverse whitelist, so _users can sign out._ This is being taken care of by myself, in a separate repo.
- External dependency: the four production workflows (Easy Hebrew, Advanced Hebrew, Easy Arabic, Advanced Arabic) need a back-end pipeline so they can be fed subjects; this is being coordinated by @wgranger 
- Note that a temporary "placeholder Subject Set" will need to be in place while that pipeline is being built.
- The Zooniverse project (`judaicadh/scribes-of-the-cairo-geniza`), web server …

Setup Production

---

src/components/ControlPanel.jsx

Attribution info is still missing in the control panel. I created a `findKey()` function in the case we needed an approximate key, to allow more flexibility with finding a key.

Add Attribution

---

src/components/ControlPanel.jsx
src/components/Home.jsx
src/components/WorkInProgressPopup.jsx
src/components/WorkflowDropdown.jsx
src/ducks/aggregations.js
src/ducks/initialize.js
src/ducks/workflow.js
src/locales/ar.js
src/locales/en.js
src/locales/he.js

This PR fixes several issues with the "Resume Progress" (i.e. retrieving data from localStorage) feature.
The fixes include:
- Resume Progress actually allows you to resume your progress!
- Prior to this PR, Resumed Progress would have been immediately overwritten by a new fetched subject. This was a conflict introduced with the recent "Select Workflow" update.
- The fix: fetchWorkflow() no longer automatically calls fetchSubject(). fetchSubject() has to be chained using a Promise.then().
- If the user either has an **active annotation** (e.g. the user started working on the Classifier, then navigated away to the About page, and now want to come back) or **saved progress** (i.e. localStorage save), the Workflow Selection dropdown now provides the option of continuing their work.
- Prior …

Fix "Resume Progress"

---

package-lock.json
package.json
src/components/ProjectHeader.jsx

This PR fixes a few small but pertinent issues:
- `panoptes-client` has been updated to `2.9.0`, which should solve login issues encountered by a few people. (Notably those with third party cookies disabled.)
- Links to the Talk and Collect links in the URL have been added. These links, of course, vary whether you're on staging or on production
Merging & deploying.

Update panoptes-client, add Talk and Collect links

---

package.json

This PR solves an issue where, if a logged in user opens a new tab/window to Scribes, the new tab/window doesn't realise that the user _should still be logged in._
This issue stemmed from Panoptes JavaScript Client 2.9.6's use of sessionStorage to keep the "user is logged in" indicator, and this sessionStorage data doesn't persist data between tabs/windows. 2.9.7 fixes this by using localStorage.
Also fixes #78 , which occurs because the user isn't logged in when they access the website on a new window/tab. (Hence, the Resume Progress prompt wouldn't trigger.)
Tests look good on localhost, deploying to production to test on a live environment and _then_ merging. (I'm so sorry, we don't have staging, and production isn't being actively used right now.)
@wgranger @snblickhan This is just a …

Update PJC to 2.9.7 so login states persist across windows/tabs

---

src/components/ControlPanel.jsx
src/components/TutorialView.jsx
src/styles/components/control-panel.styl

Two new issues from the internal beta review #72 are covered here.
- When the tutorial is on the final step, the "next" button should say "Let's Go"
- Allow subject metadata attribution to wrap on the info panel.

Address Additional Review Notes

---

src/components/Home.jsx
src/components/SelectedAnnotation.jsx
src/components/styled/FlippedImg.jsx
src/lib/ArabicKeyboard.js

Two issues are addressed in this PR:
1) The scroll image on the home page has been replaced when in rtl orientation. The original image was simply flipped, which led to the text not making sense.
2) The `alefLam` character has been changed a bit. Originally the character was only displaying one character (I believe an alef) when the character is actually the combo of the two. To account for this, the character has to try in two characters in succession (alef and lam), which will also need to advance the pointer position two spaces since the character is actually two unicode characters (see code).

Handle Language Issues

---

src/components/App.jsx
src/components/Dialog.jsx
src/components/ProjectHeader.jsx
src/components/SelectedAnnotation.jsx
src/components/StartNewWorkConfirmation.jsx
src/components/WorkInProgressPopup.jsx
src/components/WorkflowPrompt.jsx
src/components/WorkflowSelection.jsx
src/containers/SubjectViewer.jsx
src/ducks/work-in-progress.js
src/ducks/workflow.js
src/styles/components/project-header.styl

This branch does a good bit of work on the workflow selection logic. I suggest a keen eye on the changes made here, as there are a good bit and several different paths a user may take when starting a new workflow, resuming work, opening the classifier first vs. navigating from the landing page, etc. 
I also fixed a bug where a user couldn't select "done" on a `SelectedAnnotation` unless the textfield was altered.
Note: `WorkflowDropdown` was retitled as `WorkflowSelection` to better reflect what it actually is. The main changes to that component are conditions to hide all workflows unless necessary, hence the new `showAllWorkflows` prop.
~~WIP as I attempt to refactor~~

Adjust Workflow Selection Logic

---

src/components/AnnotationsPane.jsx
src/components/SelectedAnnotation.jsx
src/styles/components/dialog.styl

This PR keeps track of minor beta issues as they arise, and can be merged when needed.
Closes #88 
Currently, this branch addresses:
- Remove mention of crib sheet in `SelectedAnnotation` component instructions when transcribing Arabic.
- Fix overflow issue when viewing all scripts in `CribSheet`.
- Change color of annotation dots for a selected annotation.

Address Several Beta Issues

---

src/components/HomeStatistics.jsx
src/ducks/workflow.js

This PR finishes the stats section on the homepage. Technically, it should be ready to merge, but it is marked RFC because I'd like to optimize one aspect of the code and would like a suggestion:
1) When the stats section loads, all workflows are retrieved to correctly calculate phase two stats, which makes it unnecessary to ever fetch another workflow once these are retrieved.
2) However, the `fetchWorkflow()` function returns a promise. If we instead said in that function "instead of an api call/promise, just return that workflow, if you already have it," the `fetchWorkflow()` calls in the app break because they expect a promise return to chain the `.then()` call when `fetchSubject()` is next called.
3) Any suggestions? This code works just fine without the optimization, but it would …

Finish Stats Section

---

src/components/AdminToggle.jsx
src/components/App.jsx
src/components/Home.jsx
src/components/WorkflowSelection.jsx
src/containers/ProjectHeader.jsx
src/ducks/login.js
src/locales/ar.js
src/locales/en.js
src/locales/he.js
src/styles/components/admin-toggle.styl
src/styles/components/home-page.styl
src/styles/global/buttons.styl

closes #103 
This PR adds admin functionality, which consists of:
- Checking if logged-in user is an admin ('owner', 'collaborator', 'expert', 'researcher', 'translator')
- If so, display an Admin checkbox on the project header to toggle admin mode
- If admin mode is on, disabled workflows are enabled
ProjectHeader is also moved into the containers folder, as it seems more appropriate and a bit more organization is helpful in this repo.

Introduce Admin Mode and Toggle

---

src/components/HelperMessage.jsx
src/components/Home.jsx
src/components/Toolbar.jsx
src/containers/ClassifierContainer.jsx
src/containers/SubjectViewer.jsx
src/ducks/reminder.js
src/ducks/subject-viewer.js
src/styles/components/helper-message.styl

Closes #108 
This PR adds the "Get Started..." reminder as seen on [this](https://projects.invisionapp.com/share/37D8GSEK9#/screens/277573966) design. The component/design already existed, but functionality needed to be added to have it appear on the classifier page after some time of inactivity.
~WIP while the second reminder is added.~

Show Start and Begin Mark Reminders

---

src/components/Dialog.jsx
src/components/WorkflowSelection.jsx
src/containers/ClassifierContainer.jsx
src/containers/SubjectViewer.jsx
src/ducks/dialog.js

This PR improves the position of the transcription popup (i.e. the SelectedAnnotation component).
When the transcription popup _pops up,_ (i.e. after creating a new Annotation or clicking on an existing one) the position of the popup should NOT obscure the annotation marks, and should appear below (vertically beneath) them.
_The transcription popup appearing vertically below the annotation marks. This allows readers to read the line of text they just marked._
WIP
Currently:
- `<Dialog>` component now accepts a "default x-y offset" as an optional argument. This allows us to position the Dialog (hence, the SelectedAnnotation component) in a way that's _not_ centred on the window.
- `SubjectViewer.figureOutActualXYOfAPointInTheImage()` calculates the actual x-y coordinates (i.e. relative to …

Improve Transcription popup (SelectedAnnotation component) position

---

src/components/HelpModal.jsx
src/components/SelectedAnnotation.jsx
src/components/WorkflowSelection.jsx
src/locales/ar.js
src/locales/en.js
src/locales/he.js
src/styles/components/selected-annotation.styl
src/styles/components/text-modifier-help.styl
src/styles/global/buttons.styl

Closes #97 
This PR adds a couple help modals to the `SelectedAnnotation` component. Overall, work was done to abstract the `TextModifierHelp` component so it could be used as a general help box. The refactor work here went a little too smoothly, so I'm curious if I missed something. All appears to be working.

Add Help Modals

---

src/ducks/classification.js

Closes #96 
This PR submits the type of keyboard script and a boolean if the keyboard UI was open with each classification sent on a Hebrew manuscript. This feature should be deployed by full launch.

Submit Keyboard Information with Hebrew Manuscripts

---

src/components/ScriptReferences.jsx
src/components/Toolbar.jsx
src/containers/ClassifierContainer.jsx

This PR fixes #39 , which states that there's a potential for bad things to happen if a Timeout function attempts to use parts of React component that's not mounted (notably, this.setState()).
Technically simple, but there were shenanigans in the implementation.
1. Uh... I had to name the variables `this._isMounted` instead of `this.isMounted` because the latter actually causes the app to crash. Not kidding, this is what Chrome complained about: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Getter_only
Does anyone have insights into this? Does the `_` underscore prefix somehow make variables private vars, via Babel or React? Something something? This is one of those implicit things that I was hitherto unaware of.
2. I only checked `if (this._isMounted)` and not …

Add Timeout safety

---

src/styles/global/box-shadow.styl

This PR is a visual/design update which fixes the colour of the box shadows. All box shadows _should be_ black: `rgba(0,0,0,0.29)`.
Derp, sorry that the shadows reverted back to grey when it was supposed to be black - we kinda goofed up the standardisation of shadows in PR #82 because there were "light shadows" and "dark shadows" back then, and we picked "light shadows" as the standard. 
Minor design fix: merging and deploying.
Tagging @beckyrother for her nod of approval, high five of excellent execution, and/or solemn stare of minimal compliance.

Fix box shadows

---

package-lock.json
package.json

This PR updates `panoptes-client` to v2.11.2, which is necessary for compatibility with one of Panoptes's upcoming updates. See https://github.com/zooniverse/panoptes-javascript-client/pull/103 for further details.
Mergin' & deployin'!

Update PJC to 2.11.2 for compatibility with new Panoptes updates

---

src/containers/ProjectHeader.jsx

Closes #137 
Just removing the feedback link from the top nav. I kept the feedback translations in case we need the in the future.

Remove Feedback from Top Nav

---

src/components/FinishedPrompt.jsx
src/ducks/translations.js
src/ducks/workflow.js

We currently use local translations for the `FinishedPrompt` component. However, in order to keep content and translations for this modal flexible for project owners, the `FinishedPrompt` now renders text from Pandora. 
If there is no translation from Pandora, the modal will fallback on local translations (header and instructions) or content in the English translation (answer labels).
This is how text will render from the project builder to the modal:

Use Pandora Translations for Finished Prompt

---

src/components/AggregationsPane.jsx

With the update to FontAwesome 5, our previous solution to display an FA icon in an SVG `<text>` element no longer works. I've removed the Font Awesome className here in lieu of a more straightforward Unicode character.
You should see this icon, and the SVG overlay, if you enter the "Challenging Hebrew" workflow in staging.

Use Different "Copy" Icon for SVG Overlay

---

src/components/AnnotationKeyboard.jsx
src/components/ScriptReferences.jsx
src/components/Toolbar.jsx
src/components/about/content-intro-ar.jsx
src/components/about/content-intro-he.jsx
src/containers/ClassifierContainer.jsx
src/locales/ar.js
src/locales/en.js
src/locales/he.js

Right, so we had PR #129 which added Arabic translations _and more stuff,_ but it's been so out of date and we've had hot new translations coming in that that PR's pretty much out of sync.
Anyway, so that means _that_ PR is no longer safe to be merged, which is a problem because the aforementioned _more stuff_ includes things like translations for the words "Enter" and "Space" for the Annotation keyboard and small typo fixes for Zooniverse's reearch. So _this_ PR is a redo of _that_ PR #129, adding all the missing additions (note: I think most of the translation files are actually fine, it's just the miscellaneous _more stuff_ that's borked) but without the gooey merge conflicts.
@wgranger I'm going to need your help to review this once it's ready. Pinging @snblickhan FYI

Arabic translations update (Aug 2018), Except Properly This Time

---

src/components/FieldGuide.jsx

Translations weren't appearing for the field guide because the field guide status was never changing from `fetching`, which the `FieldGuide` component was checking for.

Fix Field Guide Translation Bug

---

package-lock.json
package.json
webpack.config.js
webpack.production.config.js

The intent of this PR is to update a number of dependencies in the project, for security purposes. This mirrors zooniverse/anti-slavery-manuscripts#291 and zooniverse/edu-api-front-end#155, with a special note of caution given ASM's penchant for the website to _look fine_ when running locally but crashing when deployed.
- Zooniverse dependencies have been updated
- `npm audit fix` was run; most notable is the updated `css-loader` which necessitated...
- ...changes to the webpack config files.
Compiles fine on localhost (+OSX+Chrome), but... you saw what happened with ASM.
Weirdly enough, to continue this test, I need to see if this works on a live web server, so I'm first going to _deploy the project_ (since we don't have staging, alas) before merging. That way, if this effs up, it's …

Update ZRC and run `npm audit fix`

---

package-lock.json
package.json

Update Zooniverse-React-Components to v0.9.1, which includes security vulnerability patches, but no changes.

Update Zooniverse-React-Components to v0.9.1

---

bin/upload.js
package-lock.json
package.json

Gets this app consistent with our other apps being updated to use s3-batch-uploads. I don't see an npm script for deploying to staging, so I don't see a good way to test this outside of the dry run flag, which has been added to the upload config script. This can be removed when ready.

Remove publisssh in favor of s3-batch-uploads

---

package-lock.json
package.json

In attempt to deploy, during build process, received the following error:
```
ERROR in ./node_modules/graphql-request/dist/index.js
Module not found: Error: Can't resolve 'graphql/language/printer'
```
This PR adds `graphql` as a dependency so `graphql-request` won't throw noted error.

Add graphql dependency for graphql-request

---

.github/workflows/deploy_production.yml
package.json

Mirror of https://github.com/zooniverse/anti-slavery-manuscripts/pull/356
This PR fixes the GitHub Action deployment. Currently, the deployment is failing due to an older version of `npm` (tied with node 14) trying to install packages from a package-lock.json created by newer versions of `npm`
- Now we're using `node 16`, which should come with the newer versions of npm
- `npm install` has also been replaced with `npm ci`

Upgrade Node to 16, fix deployment

---

package-lock.json
package.json

Upgrade `graphql` to 16.4 and `graphql-request` to 4.2.
Closes https://github.com/zooniverse/how-to-zooniverse/issues/263.

[Security] Upgrade GraphQL

---

.github/workflows/build_branch.yml
.github/workflows/deploy_production.yml
.github/workflows/deploy_staging.yml
.github/workflows/run_tests.yml

As noted in other repos using Node v16.15 or higher in builds (latest build issues in this repo are with Node v16.16) - builds with Node > 16.15 fail with unmatched peer dependency errors - new Node versions are more strict about nested dependencies.
This PR sets node to v16.14 to fix the builds.
Related to zooniverse/anti-slavery-manuscripts/pull/365 .

Update GitHub Actions to use node v16.14.x

---

src/components/about/AboutLayout.jsx
src/components/about/content-intro-ar.jsx
src/components/about/content-intro-en.jsx
src/components/about/content-intro-he.jsx

Replace `require` with `import` to fix an error where Webpack file loader outputs image URLs as `/[Object module]`.
Closes #294.

Fix broken images

---

package-lock.json
package.json

This updates panoptes-client to 4.1.0, for security purposes. This is a fairly major bump from 3.3.6, so I still need to do some local testing.

Update Panoptes-Client to 4.1.0

---

src/components/App.jsx
src/components/AppBanner.jsx
src/index.tpl.html
src/styles/components/app-banner.styl

Closes #719
This PR adds a simple banner to the Scribes of the Cairo Geniza website, to announce that transcriptions for the project is currently complete.
- A new `AppBanner` component has been added, which allows for language-switching (languge-specific messages)
- Misc: defunct polyfill service has been removed.
Merging this so @snblickhan can preview on https://scribes.preview.zooniverse.org/ . Once that gets a green light, I'll deploy.

Add "Paused Banner" (Apr 2024)
