zooniverse/scribes-of-the-cairo-geniza

src/components/App.jsx
src/components/SVGImage.jsx
src/config.js
src/containers/ClassifierContainer.jsx
src/containers/SubjectViewer.jsx
src/ducks/project.js
src/ducks/reducer.js
src/ducks/subject-viewer.js
src/ducks/subject.js
src/ducks/workflow.js
src/lib/get-subject-location.js
src/styles/components/classifier.styl
src/styles/components/control-panel.styl
src/styles/components/subject-viewer.styl
src/styles/components/toolbar.styl

This PR introduces a subject into the classifier to begin working with annotations and buttons.
12/18/2017 - Asking for an initial look over this branch to determine how subject should correctly be resized.

Introduce SVG Image to Classifier

---

package.json
src/components/App.jsx
src/components/ControlPanel.jsx
src/components/Dialog.jsx
src/components/FieldGuide.jsx
src/ducks/dialog.js
src/ducks/field-guide.js
src/ducks/reducer.js
src/lib/Utility.js
src/styles/components/dialog.styl
src/styles/components/field-guide.styl

This PR introduces the field guide into Scribes. There isn't currently a field guide attached to the production project, but the staging project should be set. This branch also creates a `Dialog` component that can be reused with other items.

Introduce Field Guide

---

src/components/ControlPanel.jsx
src/styles/components/control-panel.styl

This PR makes the right control panel more responsive on smaller screens. It also allows the panel to be hidden to allow more space for the subject viewer.
Design template can be found [here](https://projects.invisionapp.com/d/main#/console/10495701/264242741/preview).

Responsive Control Panel

---

src/components/SVGImage.jsx
src/components/Toolbar.jsx
src/containers/ClassifierContainer.jsx
src/containers/SubjectViewer.jsx
src/ducks/subject-viewer.js
src/styles/components/subject-viewer.styl

This PR adds functionality to most of the buttons on the toolbar. Although this PR is rather large, the majority of the code comes directly from ASM without changes.

Button functions

---

src/components/FavoritesButton.jsx
src/components/Toolbar.jsx
src/ducks/subject.js
src/styles/components/toolbar.styl

This PR puts the favorites button (container + component) into Scribes. Most of the code is based off ASM.

Favorites Button

---

src/config.js

This is a quick PR that updates the default workflow used by Scribes of the Cairo Geniza on staging, and the staging Panoptes App ID.
Ready for review, @wgranger 
_Side note: I'll have a separate PR to test image maps._

Update config: staging workflow ID and app ID

---

.babelrc
package-lock.json
package.json

This PR updates Babel so we can use the new ES6 Rest and Spread operators, aka the `...` operator.
While this PR doesn't add any new functionality to the website, it does bring the code up to current JavaScript/ES6 functionality, and allows some pretty code writing/duck management. (See Purpose in Scribes)
I feel that enabling `...` should be _standard_ for all our projects due to the minimum amount of work needed to get it running, and the amount of benefits it gives us in organising our code.
Rest operator works like this:
```
function test(first, second, ...theRest) {
console.log(
'The first element is ', first,
' and the second element is ', second,
' and the rest of the arguments, as an ARRAY, are ', theRest
);
}
test("hello", "world", "i can have", "as many arguments", "as I want", …
```

Add Babel's ES6 Rest/Spread operators (i.e. the triple dots: ... )

---

src/components/AnnotationKeyboard.jsx
src/components/CribSheet.jsx
src/components/SelectedAnnotation.jsx
src/containers/SubjectViewer.jsx
src/ducks/keyboard.js
src/lib/ArabicKeyboard.js
src/lib/HebrewKeyboard.js
src/lib/Utility.js
src/styles/components/annotation-keyboard.styl
src/styles/components/selected-annotation.styl

Most of the code here adds Arabic characters to the project. Implementation to type the characters works similarly to Hebrew characters, but some changes were made to streamline the two. Some changes will need to be made once workflow selection is added to the project so the correct keyboard will be added automatically. 
This keyboard was created based on an [Arabic keyboard layout editor](http://www.keyboard-layout-editor.com/#/gists/ceebf86ce67aabbaf98e8b24acdda6a6).

Implement Arabic Keyboard

---

src/components/Home.jsx
src/components/ProjectHeader.jsx
src/components/WorkflowDropdown.jsx
src/config.js
src/ducks/workflow.js
src/styles/components/project-header.styl
src/styles/components/workflow-dropdown.styl

This PR introduces workflow selection in two places: buttons on the landing page and also a dropdown menu on the project header.

Introduce Workflow Selection

---

src/components/ControlPanel.jsx
src/components/FinishedPrompt.jsx
src/components/TutorialView.jsx

This PR adds a number of small updates.
- An issue that prevented Edge and IE11 browsers from closing the tutorial box has been fixed.
- The Done & Talk now properly submits the Classification and opens the Talk window. Previously, it only did the latter.
- Translations have been applied to the Are You Finished? prompt.
Merging, deploying.

Fix Edge browser and Finished prompt issues

---

src/components/Home.jsx
src/components/SelectedAnnotation.jsx
src/locales/ar.js
src/locales/en.js
src/locales/he.js
src/styles/components/home-page.styl

This PR updates Hebrew translations as identified in #83. One issue of that PR still remains, and some Arabic translations are still missing.

Update Hebrew Translations

---

src/components/ProjectHeader.jsx

This PR adds a link for the beta feedback form to the project header.

Add Feedback Link to ProjectHeader

---

src/components/Home.jsx
src/components/WorkflowDropdown.jsx
src/styles/components/home-page.styl
src/styles/global/buttons.styl

This PR hides phase two and keyword search workflows for the Penn press release on Monday, June 11.

Hide Workflows for Press Release

---

package-lock.json
src/containers/ClassifierContainer.jsx
src/ducks/work-in-progress.js
src/styles/components/home-page.styl

This PR makes ~three~ four minor tweaks to master.
- Make sure the `WorkflowPrompt` component successfully mounts and unmounts on route change
- Tighten up button margins on main page workflow buttons
- Remove pointer cursor from inactive workflow buttons on landing page
- Updated package-lock.json
That should be about it.

Adjust Several Items for Post-Beta

---

src/components/about/content-intro-en.jsx
src/locales/ar.js
src/locales/en.js
src/locales/he.js

Closes #111 
A few minor English text updates.

Make Several English Language Changes

---

src/index.tpl.html
src/styles/components/locales.styl
src/styles/global/app-theme.styl

Closes #115 
This was the only solution I could think of to close this issue, and I'll admit, it isn't optimal, but I'm not really sure how to address it. 
@beckyrother please ping me at some point to chat about some potential unintended consequences of resolving this issue. It would be easier to show on this branch rather than explain, but basically, many of your font sizes (and in turn, element dimensions) will change with a site-wide font change.

Use Standard Hebrew and Arabic Fonts

---

src/components/AnnotationKeyboard.jsx
src/lib/HebrewKeyboard.js
src/lib/Utility.js

Closes #113 
Adds Alef Lamed character to keyboard scripts when present.

Add Alef Lamed to Hebrew Keyboard

---

package-lock.json

This PR updates the dependencies in in Scribes, via `npm audit fix`, and follows the dependency updates in #183 
Tagging @wgranger as an FYI
Merging and deploying yo!

Update dependencies - npm audit 2020

---

package-lock.json
package.json

This is a dependency update, mostly for security. Merging and deploying.

Security Update - Oct 2020

---

package-lock.json
package.json

Updates markdownz and panoptes javascript client to their latest.

Update markdownz and panoptes-client

---

.github/workflows/deploy_production.yml
.github/workflows/run_tests.yml
.travis.yml
package.json

It looks like there's no staging? @shaunanoordin is that right?

Add Github Actions. Remove Travis

---

package-lock.json

Security dependency updates

---

package-lock.json
package.json
webpack.config.js

Upgrade `webpack-dashboard` and `webpack-dev-server` so that local builds run with dev server v4.

Bump webpack-dev-server to 4

---

.github/workflows/deploy_staging.yml

Stage changes to the main branch at https://scribes.preview.zooniverse.org

Add a staging deploy

---

package-lock.json
package.json

Reverts zooniverse/scribes-of-the-cairo-geniza#322

Revert "Bump react-hot-loader from 3.0.0 to 4.13.1"

---

.github/workflows/build_branch.yml
.github/workflows/deploy_production.yml
.github/workflows/deploy_staging.yml
.github/workflows/run_tests.yml
package-lock.json
package.json

- update `package.json`.
- update GitHub workflows.

Build with Node 18 (lts/hydrogen)
